/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: hQdKsWq4NxRrjwSfk0Wbfw/Xuw5i2qZ5m1CTQ1ZiDoEjryYJomEkKQ+kiAdDQabdVQXXbM1X1l0JXPtTScq98Q==
 */

/* eslint-disable */
// tslint:disable

import SecurityPermission from './security_permission'
import SecurityRank from './security_rank'

interface SecurityRankPermission {
  permission_id: SecurityPermission['id']
  rank_id: SecurityRank['id']
}
export default SecurityRankPermission;

interface SecurityRankPermission_InsertParameters {
  permission_id: SecurityPermission['id']
  rank_id: SecurityRank['id']
}
export type {SecurityRankPermission_InsertParameters}
