/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Jxum5uzEZDgUZnvSIw5md2xHh5qOZM79RrhGEtC2UaIDhStdzVwmKoSor9US3mEIxQN5jnY4kpPMjq3Fsgh1VA==
 */

/* eslint-disable */
// tslint:disable

interface SecurityRank {
  id: number & {readonly __brand?: 'security_rank_id'}
  name: (string) | null
}
export default SecurityRank;

interface SecurityRank_InsertParameters {
  id: number & {readonly __brand?: 'security_rank_id'}
  name?: (string) | null
}
export type {SecurityRank_InsertParameters}
