/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: qnXDJl+PwgUe/hTZCtFakuo7VyVCr8X7FlkBuJ69sCLcfSmo+dGtZvar6NyibhmeRmCFDBJPqFWAkyRm4lIXlA==
 */

/* eslint-disable */
// tslint:disable

import SecurityRank from './security_rank'

interface User {
  email: (string) | null
  first_name: (string) | null
  id: number & {readonly __brand?: 'user_id'}
  last_name: (string) | null
  password: string
  password_hash: string
  rank: (SecurityRank['id']) | null
  username: (string) | null
}
export default User;

interface User_InsertParameters {
  email?: (string) | null
  first_name?: (string) | null
  id: number & {readonly __brand?: 'user_id'}
  last_name?: (string) | null
  password: string
  password_hash: string
  rank?: (SecurityRank['id']) | null
  username?: (string) | null
}
export type {User_InsertParameters}
